### ISSUE TITLE
Error about loading ashawkey/zero123-xl-diffusers

### ISSUE THREAD

**Issue by ZhenyuSun-Walker** [HansenHuang0823/PlacidDreamer#1]
Hello, I find difficulties in running  
` python imagetomesh.py --elev 10 --im_path cactus.png. `
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory ashawkey/zero123-xl-diffusers/image_encoder.

However, there is no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack originally in the direction. I have downloaded the correct model locally, but the error occurs.

Would you mind giving me some suggestions? Anticipating for your early reply!

**Comment by skipper17** [comment]
Please use `bennyguo/zero123-xl-diffusers`.

**Comment by ZhenyuSun-Walker** [comment]
Thank you for your timely suggestions! However, I find that there is no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack either in bennyguo/zero123-xl-diffusers. Anyway, I‘ll try it and contact with you later!

**Comment by ZhenyuSun-Walker** [comment]
It seems that your solution works well! Thank you for your assistances!

**Comment by HansenHuang0823** [comment]
Thank you for bringing this to our attention. Sorry for the oversight and any inconvenience it may have caused.
