### ISSUE TITLE
How to control the port?

### ISSUE THREAD

**Issue by ZhenyuSun-Walker** [HansenHuang0823/PlacidDreamer#2]

**Comment by ZhenyuSun-Walker** [comment]
Hello! I'm facing the problem when running `sh train_dreambooth_lora.sh`. The warning is `Traceback (most recent call last):
  File "/home/sunzhenyu/anaconda3/envs/PlacidDreamer/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/sunzhenyu/anaconda3/envs/PlacidDreamer/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/sunzhenyu/anaconda3/envs/PlacidDreamer/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1088, in launch_command
    multi_gpu_launcher(args)
  File "/home/sunzhenyu/anaconda3/envs/PlacidDreamer/lib/python3.10/site-packages/accelerate/commands/launch.py", line 711, in multi_gpu_launcher
    current_env = prepare_multi_gpu_env(args)
  File "/home/sunzhenyu/anaconda3/envs/PlacidDreamer/lib/python3.10/site-packages/accelerate/utils/launch.py", line 190, in prepare_multi_gpu_env
    raise ConnectionError(
ConnectionError: Tried to launch distributed communication on port `29500`, but another process is utilizing it. Please specify a different port (such as using the `--main_process_port` flag or specifying a different `main_process_port` in your config file) and rerun your script. To automatically use the next open port (on a single node), you can set this to `0`.`

How can I control the port?

**Comment by HansenHuang0823** [comment]
Maybe you can add “--main_process_port 0” or manually set up the accelerate config.

**Comment by ZhenyuSun-Walker** [comment]
I've tried `--main_process_port 0`, but it doesn't work. Would you mind guiding me how to set up the accelerate config for mannual port selection?

**Comment by HansenHuang0823** [comment]
You can try not setting the `main_process_port` to 0, but set it to 29498. You can also enter `accelerate config` in the command line, set it to single GPU, and turn off all acceleration options. I'm on vacation, sorry I can't provide more detailed guidance. You can search for the documentation on `accelerate config`.

**Comment by ZhenyuSun-Walker** [comment]
I greatly appreciate your guidance and suggestions! Your help is invaluable to me. Enjoy your vacation, and I look forward to your continued guidance when you return.

**Comment by HansenHuang0823** [comment]
Have you solved the problem?

**Comment by ZhenyuSun-Walker** [comment]
I apologize for the late response, the issue has not yet been resolved.

**Comment by ZhenyuSun-Walker** [comment]
Right now I just retried the commands `sh train_dreambooth_lora.sh` , and now it works well!

**Comment by HansenHuang0823** [comment]
I'm glad to hear that! If you encounter any more issues or have further questions, feel free to ask.
